#FROM node:16-alpine
#VOLUME /golem/input
#WORKDIR /golem/work

FROM python:3.8.7-slim
VOLUME /golem/input
WORKDIR /golem/work

# https://handbook.golem.network/requestor-tutorials/task-processing-development/task-example-1-cracker